### ISSUE TITLE
Install on Windows 7

### ISSUE THREAD

**Issue by cgarneata** [kingpong/ruby-mcrypt#3]
Running into some issues setting up the gem on Windows 7. It might be that I just don't setup mcrypt correctly. I basically download libmcrypt from sourceforge and point to it on install.

gem install kingpong-ruby-mcrypt --source=http://gems.github.com -- --with-mcrypt-dir=C:\Progra~2\libmcrypt-2.5.8

And this is the error I get:

ERROR:  Error installing kingpong-ruby-mcrypt:
ERROR: Failed to build gem native extension.

C:/PROGRA~2/Ruby193/bin/ruby.exe extconf.rb --with-mcrypt-dir=C:\Progra~2\libmcrypt-2.5.8
checking for mcrypt.h... yes
checking for mcrypt_module_open() in -lmcrypt... no

Unable to find your mcrypt library.

And in the mkmf.log:

conftest.c:7:53: error: 'mcrypt_module_open' undeclared (first use in this function)

Thanks for your help!

**Comment by kingpong** [comment]
Sorry, I can't help with installing on Windows since at the time I wrote this module, the assumed environment for Ruby was *nix. I'm glad if you can do it but I can't offer any assistance.
