### ISSUE TITLE
Serious bug with rijndael 256: input is not a multiple of the block size (32)

### ISSUE THREAD

**Issue by jonathantribouharet** [kingpong/ruby-mcrypt#5]
Hi,
I'm currently having a serious bug:

```
iv_size = 32
iv = OpenSSL::Random.random_bytes(iv_size)
secret = 'zqrhpx458ot9p9hlm5gevjw5nr0adf57'
data = JSON.dump({"test" => "Méré"})

cipher = Mcrypt.new(:rijndael_256, :cbc, secret, iv, :zeros)
cipher2 = Mcrypt.new(:rijndael_256, :cbc, secret, iv, :zeros)

cipher2.decrypt(cipher.encrypt(data))
```

I have the error: `input is not a multiple of the block size (32)`

**Comment by jonathantribouharet** [comment]
The problem seems to come from "Méré", the accent.

**Comment by cfaguayo** [comment]
Hi @jonathantribouharet ,

I have currently the same problem, cannot make it work for accented characters. Have you got a solution for this?

I would appreciate your help.

**Comment by jonathantribouharet** [comment]
Sorry, I don't. I removed all non ASCII characters from the string with the method `transliterate ` from Rails, even if 'é' is an ASCII characters. Maybe you just have to encode your string.
I have to use mcrypt for communicate with an old API for payment, the accent wasn't very important.
If you control the cipher et decipher you may convert your string in base64.

**Comment by kingpong** [comment]
Sorry this is a few years late, but just commenting here in case anyone else runs into this problem.

My ruby knowledge is pretty stale but I believe ruby interpreters starting with 1.9 associate an encoding with strings. This mcrypt gem was written for ruby 1.8 so it's not very sophisticated in that regard.  You'll need to use a binary encoded string for this to work properly.  You can encode the string, or read it from a file opened with `File.open(...,'rb')`. 

Updated example that works. I put the UTF-8 encoded JSON in data.json:

```ruby
require 'mcrypt'

iv_size = 32
iv = 0.upto(iv_size-1).to_a

secret = 'zqrhpx458ot9p9hlm5gevjw5nr0adf57'
data = File.open('data.json', 'rb') { |f| f.read }

cipher = Mcrypt.new(:rijndael_256, :cbc, secret, iv, :zeros)
cipher2 = Mcrypt.new(:rijndael_256, :cbc, secret, iv, :zeros)

print cipher2.decrypt(cipher.encrypt(data))

# prints:
# {"test":"Méré"}
```
