### ISSUE TITLE
Is it possible to send an array as the key and value to be encrypted?

### ISSUE THREAD

**Issue by gabrieltal** [kingpong/ruby-mcrypt#8]
hello!

I have been trying to use an array as the key and the value to be encrypted. It will let me use an array as the key just fine. But when I try to encrypt an array it gives me errors. I have a SO question but no answers and the comments haven't been helpful so far. https://stackoverflow.com/q/54011153/9911698. 

Here is specifically what I'm running.
```
require 'mcrypt'

def encrypt(plain, secret)
  cipher = Mcrypt.new("rijndael-256", :ecb, secret)
  cipher.padding = :zeros

  encrypted = cipher.encrypt(plain)
  p encrypted
  encrypted.unpack("H*").first.to_s.upcase
end

array_to_encrypt = [16, 0, 0, 0, 50, 48, 49, 55, 47, 48, 50, 47, 48, 55, 32, 50, 50, 58, 52, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
key_array = [65, 66, 67, 68, 49, 50, 51, 52, 70, 71, 72, 73, 53, 54, 55, 56]

result = encrypt(array_to_encrypt, key_array)
p "RESULT IS #{result}"
```

The output is as follows:
```
Mcrypt::RuntimeError: Could not initialize mcrypt: Key length is not legal.
```

Is what I'm trying to do even possible? Can I use an array as the key and encrypt an array as well? Thanks for any help you can provide!

**Comment by kingpong** [comment]
@gabrieltal no, it's not possible to use arrays directly.  You'll need to encode them as binary strings.  I've given [an example](https://stackoverflow.com/a/54080799/161183) on your stackoverflow question.
